<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=shift-jis">
  <title>OutOfBoundsException クラス</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs"><div class="manualnavbar" style="text-align: center;">
 <div class="prev" style="text-align: left; float: left;"><a href="class.logicexception.html">LogicException</a></div>
 <div class="next" style="text-align: right; float: right;"><a href="class.outofrangeexception.html">OutOfRangeException</a></div>
 <div class="up"><a href="spl.exceptions.html">例外</a></div>
 <div class="home"><a href="index.html">PHP Manual</a></div>
</div><hr /><div id="class.outofboundsexception" class="reference">
 <h1 class="title">OutOfBoundsException クラス</h1>
 
 
 <div class="partintro"><p class="verinfo">(PHP 5 &gt;= 5.1.0, PHP 7)</p>
 

  <div class="section" id="outofboundsexception.intro">
   <h2 class="title">はじめに</h2>
   <p class="para">
    値が有効なキーでなかった場合にスローされる例外です。
    これは、コンパイル時には検出できないエラーです。
   </p>
  </div>

 
  <div class="section" id="outofboundsexception.synopsis">
   <h2 class="title">クラス概要</h2>
 

   <div class="classsynopsis">
    <div class="ooclass"></div>
 

    <div class="classsynopsisinfo">
     <span class="ooclass">
      <strong class="classname">OutOfBoundsException</strong>
     </span>
 
    <span class="ooclass">
      <span class="modifier">extends</span>
      <a href="class.runtimeexception.html" class="classname">RuntimeException</a>
     </span>
     {</div>

 
    <div class="classsynopsisinfo classsynopsisinfo_comment">/* 継承したプロパティ */</div>
    <div class="fieldsynopsis">
     <span class="modifier">protected</span>
     <span class="type">string</span>
      <var class="varname"><a href="class.exception.html#exception.props.message">$<var class="varname">message</var></a></var>
    ;</div>
<div class="fieldsynopsis">
     <span class="modifier">protected</span>
     <span class="type">int</span>
      <var class="varname"><a href="class.exception.html#exception.props.code">$<var class="varname">code</var></a></var>
    ;</div>
<div class="fieldsynopsis">
     <span class="modifier">protected</span>
     <span class="type">string</span>
      <var class="varname"><a href="class.exception.html#exception.props.file">$<var class="varname">file</var></a></var>
    ;</div>
<div class="fieldsynopsis">
     <span class="modifier">protected</span>
     <span class="type">int</span>
      <var class="varname"><a href="class.exception.html#exception.props.line">$<var class="varname">line</var></a></var>
    ;</div>



   <div class="classsynopsisinfo classsynopsisinfo_comment">/* 継承したメソッド */</div>
    <div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="exception.getmessage.html" class="methodname">Exception::getMessage</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">Exception</span> <span class="methodname"><a href="exception.getprevious.html" class="methodname">Exception::getPrevious</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">mixed</span> <span class="methodname"><a href="exception.getcode.html" class="methodname">Exception::getCode</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="exception.getfile.html" class="methodname">Exception::getFile</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">int</span> <span class="methodname"><a href="exception.getline.html" class="methodname">Exception::getLine</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">array</span> <span class="methodname"><a href="exception.gettrace.html" class="methodname">Exception::getTrace</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">public</span> <span class="type">string</span> <span class="methodname"><a href="exception.gettraceasstring.html" class="methodname">Exception::getTraceAsString</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">public</span> <span class="type">string</span>  <span class="methodname"><a href="exception.tostring.html" class="methodname">Exception::__toString</a></span>
    ( <span class="methodparam">void</span>
   )</div>
<div class="methodsynopsis dc-description">
   <span class="modifier">final</span> <span class="modifier">private</span> <span class="type">void</span> <span class="methodname"><a href="exception.clone.html" class="methodname">Exception::__clone</a></span>
    ( <span class="methodparam">void</span>
   )</div>

   }</div>

 
  </div>
 
 </div>
 
 
 
</div>
<div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="121092""></a>
  <div class="note">
   <strong class="user">Jakub Adamczyk</strong>
   <a href="#121092" class="date">17-May-2017 08:35</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
I see this in this way:<br />
By definiton, OutOfRangeException should be use to when potential problem is logical. This (OutOfBoundsException) is for runtime, so it's perfect for catching errors which occur because of bad result from database and simillar.<br />
<br />
Example of using OutOfBoundSException (see also note in "OutOfRangeException class" article):<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">HandleApplication </span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$_POST</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if(!isset(</span><span class="default">$_POST</span><span class="keyword">[</span><span class="string">'secretCode'</span><span class="keyword">])<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">OutOfBoundsException</span><span class="keyword">(</span><span class="string">'Application hasn'</span><span class="default">t sent secret code </span><span class="keyword">for </span><span class="default">authenticate</span><span class="string">');<br />
}</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="120533""></a>
  <div class="note">
   <strong class="user">evguenia dot chagnon at gmail dot com</strong>
   <a href="#120533" class="date">26-Jan-2017 09:58</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
class MyDynamicTastyPie implements ArrayAccess{<br />
&nbsp;&nbsp;&nbsp; private $_pointeur = 0;<br />
&nbsp;&nbsp;&nbsp; private $_array = ['strawberry slice','white chocolate','nuts'];<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetExists($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return isset($this-&gt;_array[$key]);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetGet($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if ($key &gt; count($this-&gt;_array)){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new OutOfBoundsException('Your tasty pie doesn\'t contain so slices');<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return $this-&gt;_array[$key];<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetSet($key, $value){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $this-&gt;_array[$key] =$value;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetUnset($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; unset($this-&gt;_array[$key]);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function addSlice($slice){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $this-&gt;_array[] = $slice;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; $myDynamicTastyPie = new MyDynamicTastyPie();<br />
&nbsp;&nbsp;&nbsp; $myDynamicTastyPie-&gt;addSlice('Black chocolate cream decoration');<br />
&nbsp;&nbsp;&nbsp; echo $myDynamicTastyPie[7];<br />
}<br />
catch(OutOfBoundsException $e){<br />
&nbsp;&nbsp;&nbsp; echo 'Here is your OutOfBoundsException!';<br />
}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="119547""></a>
  <div class="note">
   <strong class="user">sricharan dot krishnan at gmail dot com</strong>
   <a href="#119547" class="date">04-Jul-2016 07:48</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
An example where an OutOfBoundsException can occur:<br />
Lets say post a certain division process, we wish to access a value in an Array [provided ofcourse if the result value of the division is within the size of the Array]..<br />
<br />
try{<br />
&nbsp;&nbsp;&nbsp; if ($iNum2 == 0){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new Exception("Division by Zero");<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; $iResult = $iNum1 / $iNum2;<br />
&nbsp;&nbsp;&nbsp; echo ("Division result is: ".($iResult)."&lt;br/&gt;");<br />
}<br />
catch (Exception $e){<br />
&nbsp;&nbsp;&nbsp; echo ("Division by Zero is not possible.".($e)."&lt;br/&gt;");<br />
}<br />
<br />
$rg_Array = array(1,2,3,4);<br />
<br />
try{<br />
&nbsp;&nbsp;&nbsp; if ($iResult &gt; sizeof($rg_Array)- 1){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new Exception("Exceeding key values");<br />
&nbsp;&nbsp;&nbsp; }<br />
echo ("Capturing value from \$rg_Array post Division process:".($rg_Array[$iResult])."&lt;br/&gt;");<br />
}<br />
catch (Exception $e){<br />
&nbsp;&nbsp;&nbsp; echo ("Value of Division result is out of bounds for the array.".($e)."&lt;br/&gt;");<br />
}<br />
?&gt;</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="117790""></a>
  <div class="note">
   <strong class="user">Jacob V. Rasmussen</strong>
   <a href="#117790" class="date">11-Aug-2015 05:49</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
OutOfRangeException is for Integers out of range.
<br />
OutOfBoundsException is for key values, not found in the target array.
<br />

<br />
Editor's note: This is incorrect; OutOfRangeException has *nothing* to do with Integer ranges. I decided to keep this highly voted comment even though it is wrong for education's sake.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="116103""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#116103" class="date">10-Nov-2014 12:29</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
i wish i know what's the difference between <br />
OutOfRangeException and OutOfBoundsException lol</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
<hr /><div class="manualnavbar" style="text-align: center;">
 <div class="prev" style="text-align: left; float: left;"><a href="class.logicexception.html">LogicException</a></div>
 <div class="next" style="text-align: right; float: right;"><a href="class.outofrangeexception.html">OutOfRangeException</a></div>
 <div class="up"><a href="spl.exceptions.html">例外</a></div>
 <div class="home"><a href="index.html">PHP Manual</a></div>
</div></body></html>
